[package]
name = "riemann_client"
version = "0.3.1"
license = "MIT"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "A Riemann client library"
repository = "https://github.com/borntyping/rust-riemann_client"

[dependencies]
log = "^0.3.1"
libc = "^0.1.6"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"
version = "^0.0.9"

[dev-dependencies]
simple_logger = "^0.3.1"
