[package]
name = "riemann_client"
version = "0.2.2"
license = "MIT"
authors = ["Sam Clements <sam@borntyping.co.uk>"]
description = "A Riemann client library"
repository = "https://github.com/borntyping/rust-riemann_client"

[dependencies]
log = "^0.3.0"
libc = "^0.1.3"

[dependencies.protobuf]
path = "vendor/protobuf"
version = "^0.0.9"

[dev-dependencies]
simple_logger = "^0.3.0"
